version = 0.1
[default.deploy.parameters]
stack_name = "visory-engineering-challenge-backend"
resolve_s3 = true
s3_prefix = "visory-engineering-challenge-backend"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
