AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  GetTicketmasterEventsFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'src/ticketMasterEventService/handler.handler'
      Runtime: 'nodejs20.x'
      Timeout: 10
      MemorySize: 1024
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - 'secretsmanager:GetSecretValue'
              Resource: 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:ticketmaster_api_key'
      Events:
        Api:
          Type: 'Api'
          Properties:
            Path: '/getTicketmasterEvents'
            Method: 'get'